import assert from 'node:assert/strict';
import { defaultDoorLine } from './door-line-contract';
import { applyManualGeometryOverride, calculateGlassGeometry, removeManualGeometryOverride, withDerivedGlassGeometry } from './glass-geometry-contract';
import { nextGlassBuilderDraft } from './glass-editor-contract';
import type { DoorLineInput } from './job-intake-types';

const line: DoorLineInput = { ...defaultDoorLine('Exterior'), lineId: '11111111-1111-4111-8111-111111111111', config: 'SD', roWidth: '60', roHeight: '84', sidelightType: 'Glass', sidelightGlass: 'CLR_SB60_K4SG' };
const calculated = calculateGlassGeometry(line);
assert.equal(calculated.status, 'Warning');
const request = { line, accessLevel: 'use' as const, acceptedValues: calculated.glassCalc!, reason: 'Verified opening', actorUserId: 'tester', appliedAt: '2026-09-28T12:00:00Z' };
assert.throws(() => applyManualGeometryOverride({ ...request, reason: '  ' }));
assert.throws(() => applyManualGeometryOverride({ ...request, line: { ...line, roWidth: '12' } }));
assert.throws(() => applyManualGeometryOverride({ ...request, accessLevel: 'view' }));
const approval = applyManualGeometryOverride(request);
const approved = calculateGlassGeometry({ ...line, glassOverride: approval });
assert.equal(approved.status, 'Manual Override');
assert.deepEqual(approved.glassCalc, calculated.glassCalc);
assert.deepEqual(approved.glassUnits, calculated.glassUnits);
const historical = { ...approval, acceptedValues: { headerWidth: '999', transomHeight: '999' } };
const historicalLine = withDerivedGlassGeometry({ ...line, glassOverride: historical });
assert.deepEqual(historicalLine.glassOverride?.acceptedValues, historical.acceptedValues);
assert.deepEqual(historicalLine.glassCalc, calculated.glassCalc);
assert.deepEqual(calculateGlassGeometry({ ...historicalLine, glassOverride: removeManualGeometryOverride('use') }).glassCalc, calculated.glassCalc);
assert.equal(calculateGlassGeometry({ ...line, roWidth: '61', glassOverride: approval }).override, null);
assert.equal(calculateGlassGeometry({ ...line, lineId: 'other', glassOverride: approval }).override, null);
assert.equal(calculateGlassGeometry({ ...line, roWidth: '12', glassOverride: approval }).status, 'Blocked');
assert.equal(nextGlassBuilderDraft({ ...line, glassOverride: approval }, 'roWidth', '61').glassOverride, null);
assert.equal(calculateGlassGeometry({ ...line, glassOverride: { ...approval, calculatedValues: Object.fromEntries(Object.entries(approval.calculatedValues).reverse()) } }).status, 'Manual Override', 'Object key order does not invalidate historical snapshots');
console.log('Geometry exception approval / historical audit / stale snapshot protection: PASS');
