import assert from 'node:assert/strict';
import { changeSizingMode } from './door-line-editor-state';
import { defaultDoorLine, normalizeDoorLineInput } from './door-line-contract';
import { calculateNonGlassFrameCut } from './non-glass-frame-cut-contract';
import { calculateGlassGeometry } from './glass-geometry-contract';
import type { DoorLineInput } from './job-intake-types';

const standard = { ...defaultDoorLine('Exterior'), config: 'DD' };
const custom: DoorLineInput = { ...changeSizingMode(standard, 'WoodCustom'), doubleDoorSizing: { kind: 'custom-slabs', activeWidth: '41-3/4', inactiveWidth: '35-3/4', height: '79' } };
assert.equal(calculateNonGlassFrameCut(custom).values?.headerWidth?.inches, 78.5625);
assert.equal(calculateNonGlassFrameCut(custom).values?.recommendedRoWidth?.inches, 80.5625);
const fit = { ...changeSizingMode(custom, 'RO'), roWidth: '74' };
assert.equal(fit.doubleDoorSizing, null);
const cut = calculateNonGlassFrameCut(fit);
assert.equal(cut.values?.activeLeafWidth?.inches, 35.75);
assert.equal(cut.values?.inactiveLeafWidth?.inches, 35.1875);
assert.equal(cut.values?.widthCutDown?.inches, .5625);
const normalized = normalizeDoorLineInput(fit);
assert.ok(normalized.ok);
assert.equal(normalized.value.doubleDoorSizing, null);
assert.equal(normalized.value.customSlabWidth, null);
assert.equal(normalized.value.customSlabHeight, null);
const back = changeSizingMode(fit, 'WoodCustom');
assert.equal(back.roWidth, '');
assert.equal(back.roHeight, '');
assert.equal(normalizeDoorLineInput(back).ok, false, 'New custom inputs are required');
const off = changeSizingMode(custom, 'No');
assert.equal(off.doubleDoorSizing, null);
assert.equal(calculateNonGlassFrameCut(off).values?.headerWidth?.inches, 72.5625);
assert.equal(off.customSlab, 'No');
assert.equal(changeSizingMode({ ...standard, doubleDoorSizing: { kind: 'actual-leaves', activeWidth: 41.75, inactiveWidth: 35.75 } }, 'RO').doubleDoorSizing, null);
const glass: DoorLineInput = { ...custom, config: 'T/DD', roWidth: '80 9/16', roHeight: '95', transomGlassTypeCode: 'CLEAR' };
const glassFit = changeSizingMode(glass, 'RO');
assert.equal(glassFit.roWidth, glass.roWidth, 'Glass RO stays available');
assert.equal(calculateGlassGeometry(glassFit).glassCalc?.activeLeafWidth, '35 3/4"');
const glassOff = changeSizingMode(glassFit, 'No');
assert.equal(glassOff.roHeight, '95');
assert.equal(calculateGlassGeometry(glassOff).glassCalc?.headerWidth, '72 9/16"');
console.log('Mutually exclusive sizing modes: PASS');
