-- ROLLBACK-CONTAINED DIRECT-DIMENSION GLASS RPC ACCEPTANCE
-- TEST DATA MUST NOT PERSIST
-- MUST NOT CALL NATIVE SEQUENCE ALLOCATION
-- DO NOT CHANGE ROLLBACK TO COMMIT
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';
DO $acceptance$
DECLARE
 v_actor uuid; v_actor_count integer; v_seq bigint; v_seq_called boolean; v_after_sequence bigint; v_after_called boolean; v_job uuid; v_revision bigint;
 v_error text; v_result jsonb; v_replay jsonb; v_case record; v_bad jsonb; v_case_index integer:=0;
 v_header jsonb:=pg_catalog.jsonb_build_object('customer','NON-PRODUCTION TEST – DO NOT BUILD OR SCHEDULE','lifecycle_stage','Draft','notes','NON-PRODUCTION TEST – DO NOT BUILD OR SCHEDULE');
 v_specs jsonb:='[{"side":"left","index":1,"finishedWidth":"11-3/4\"","tBarSize":"1.5","glassTypeCode":"CLEAR"},{"side":"right","index":2,"finishedWidth":"13 5/8\"","tBarSize":"2.25","glassTypeCode":"CUSTOM","customGlassDescription":"NON-PRODUCTION TEST GLASS","panelSizeMode":"custom","panelConstructionNotes":"NON-PRODUCTION TEST PANEL"}]'::jsonb;
 v_line jsonb;
 v_provenance jsonb:=pg_catalog.jsonb_build_object('direction','legacy_to_native','source_system','legacy-doorgo','source_job_state','active','transfer_schema','doorgo.legacy-job-transfer','transfer_version',1,'source_identifier_kind','legacy_job_id','source_identifier_value','NONPROD-DDG-TRANSFER-980001','source_saved_at','2026-08-05T00:00:00Z','exported_at','2026-08-05T00:01:00Z','source_fingerprint',pg_catalog.repeat('a',64));
BEGIN
 SELECT pg_catalog.count(*) INTO v_actor_count
 FROM public.dg_user_profiles profile JOIN public.dg_user_permissions permission ON permission.user_id=profile.user_id
 WHERE profile.active=true AND permission.permission_key='jobs' AND permission.access_level='use';
 IF v_actor_count<>1 THEN RAISE EXCEPTION 'acceptance.exactly_one_jobs_use_actor_required'; END IF;
 SELECT profile.user_id INTO v_actor FROM public.dg_user_profiles profile JOIN public.dg_user_permissions permission ON permission.user_id=profile.user_id WHERE profile.active=true AND permission.permission_key='jobs' AND permission.access_level='use';
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',v_actor::text,true);
 PERFORM pg_catalog.set_config('request.jwt.claim.role','authenticated',true);
 SELECT last_value,is_called INTO v_seq,v_seq_called FROM public.dg_native_job_reference_seq;
 IF EXISTS(SELECT 1 FROM public.dg_native_jobs WHERE visible_identifier IN ('NONPROD-DDG-NATIVE-980001','NONPROD-DDG-TRANSFER-980001'))
   OR EXISTS(SELECT 1 FROM public.dg_native_job_create_commands WHERE command_id::text LIKE 'd1a00000-0000-4000-8000-%')
   OR EXISTS(SELECT 1 FROM public.dg_native_job_lines WHERE line_id::text LIKE 'd1b00000-0000-4000-8000-%')
 THEN RAISE EXCEPTION 'acceptance.synthetic_identity_collision'; END IF;
 v_line:=pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000001','line_index',1,'line_status','Active','mode','Interior','config','D','width','2''6"','height','6''8"','qty',1,'notes','NON-PRODUCTION TEST – DO NOT BUILD OR SCHEDULE','sidelight_specifications',v_specs,'transom_t_bar_size','1.5','transom_glass_type_code','CUSTOM','transom_custom_glass_description','NON-PRODUCTION TEST TRANSOM');
 v_result:=public.dg_create_native_job('d1a00000-0000-4000-8000-000000000001','legacy_transfer','NONPROD-DDG-NATIVE-980001','biztrack_sales_order',v_header,pg_catalog.jsonb_build_array(v_line));
 v_job:=(v_result#>>'{job,internal_job_id}')::uuid; v_revision:=(v_result#>>'{job,revision}')::bigint;
 IF v_result#>'{lines,0,sidelight_specifications}'<>v_specs OR v_result#>>'{lines,0,transom_t_bar_size}'<>'1.5' OR v_result#>>'{lines,0,transom_glass_type_code}'<>'CUSTOM' OR v_result#>>'{lines,0,config}'<>'D' THEN RAISE EXCEPTION 'acceptance.native_create_persistence_failed'; END IF;
 v_replay:=public.dg_create_native_job('d1a00000-0000-4000-8000-000000000001','legacy_transfer','NONPROD-DDG-NATIVE-980001','biztrack_sales_order',v_header,pg_catalog.jsonb_build_array(v_line));
 IF v_replay->>'idempotent_replay'<>'true' THEN RAISE EXCEPTION 'acceptance.native_idempotent_replay_failed'; END IF;
 BEGIN PERFORM public.dg_create_native_job('d1a00000-0000-4000-8000-000000000001','legacy_transfer','NONPROD-DDG-NATIVE-980001','biztrack_sales_order',v_header||'{"phone":"changed"}'::jsonb,pg_catalog.jsonb_build_array(v_line));RAISE EXCEPTION 'idempotency_not_rejected';EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error NOT LIKE '%idempotency_conflict%' THEN RAISE;END IF;END;
 v_result:=public.dg_update_native_job(v_job,v_revision,v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('sidelight_specifications',NULL,'transom_t_bar_size','2.25','transom_glass_type_code','CLEAR','transom_custom_glass_description',NULL)));
 IF (v_result#>>'{job,revision}')::bigint<>v_revision+1 OR v_result#>'{lines,0,sidelight_specifications}'<>'[]'::jsonb OR v_result#>>'{lines,0,transom_t_bar_size}'<>'2.25' OR v_result#>>'{job,customer}'<>v_header->>'customer' THEN RAISE EXCEPTION 'acceptance.update_failed';END IF;
 BEGIN PERFORM public.dg_update_native_job(v_job,v_revision,v_header,pg_catalog.jsonb_build_array(v_line));RAISE EXCEPTION 'stale_revision_not_rejected';EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error NOT LIKE '%stale_revision%' THEN RAISE;END IF;END;
 v_result:=public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000002',v_provenance,v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000002')));
 IF v_result#>'{lines,0,sidelight_specifications}'<>v_specs OR v_result#>>'{job,transfer_source_fingerprint}'<>pg_catalog.repeat('a',64) THEN RAISE EXCEPTION 'acceptance.transferred_create_failed';END IF;
 v_replay:=public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000002',v_provenance,v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000002')));IF v_replay->>'idempotent_replay'<>'true' THEN RAISE EXCEPTION 'acceptance.transfer_replay_failed';END IF;
 BEGIN PERFORM public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000002',v_provenance,v_header||'{"phone":"changed"}'::jsonb,pg_catalog.jsonb_build_array(v_line));RAISE EXCEPTION 'transfer_idempotency_not_rejected';EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error NOT LIKE '%idempotency_conflict%' THEN RAISE;END IF;END;
 v_result:=public.dg_create_native_job('d1a00000-0000-4000-8000-000000000003','legacy_transfer','NONPROD-DDG-OLD-980001','biztrack_sales_order',v_header,pg_catalog.jsonb_build_array(v_line-'sidelight_specifications'-'transom_t_bar_size'-'transom_glass_type_code'-'transom_custom_glass_description'||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000003')));IF v_result#>'{lines,0,sidelight_specifications}'<>'[]'::jsonb OR v_result#>>'{lines,0,transom_t_bar_size}' IS NOT NULL THEN RAISE EXCEPTION 'acceptance.old_payload_compatibility_failed';END IF;
 FOR v_case IN SELECT * FROM (VALUES
  ('unsupported_t_bar','{"sidelight_specifications":[{"side":"left","index":1,"tBarSize":"3"}]}'::jsonb),('numeric_t_bar','{"sidelight_specifications":[{"side":"left","index":1,"tBarSize":1.5}]}'::jsonb),('duplicate_identity','{"sidelight_specifications":[{"side":"left","index":1},{"side":"left","index":1}]}'::jsonb),('missing_side','{"sidelight_specifications":[{"index":1}]}'::jsonb),('string_index','{"sidelight_specifications":[{"side":"left","index":"1"}]}'::jsonb),('fractional_index','{"sidelight_specifications":[{"side":"left","index":1.5}]}'::jsonb),('outside_index','{"sidelight_specifications":[{"side":"left","index":4}]}'::jsonb),('unsupported_width','{"sidelight_specifications":[{"side":"left","index":1,"finishedWidth":"12cm"}]}'::jsonb),('blank_width','{"sidelight_specifications":[{"side":"left","index":1,"finishedWidth":" "}]}'::jsonb),('unknown_glass','{"sidelight_specifications":[{"side":"left","index":1,"glassTypeCode":"BLUE"}]}'::jsonb),('custom_without_description','{"sidelight_specifications":[{"side":"left","index":1,"glassTypeCode":"CUSTOM"}]}'::jsonb),('invalid_description_scalar','{"sidelight_specifications":[{"side":"left","index":1,"customGlassDescription":12}]}'::jsonb),('unsupported_panel_mode','{"sidelight_specifications":[{"side":"left","index":1,"panelSizeMode":"wide"}]}'::jsonb),('unexpected_key','{"sidelight_specifications":[{"side":"left","index":1,"unknown":true}]}'::jsonb),('non_array','{"sidelight_specifications":{}}'::jsonb),('invalid_transom_tbar','{"transom_t_bar_size":"3"}'::jsonb),('invalid_transom_glass','{"transom_glass_type_code":"BLUE"}'::jsonb)) t(label,payload)
 LOOP v_case_index:=v_case_index+1;v_bad:=v_line||v_case.payload||pg_catalog.jsonb_build_object('line_id',('d1b00000-0000-4000-8000-'||pg_catalog.lpad((100+v_case_index)::text,12,'0')));BEGIN PERFORM public.dg_update_native_job(v_job,v_revision+1,v_header,pg_catalog.jsonb_build_array(v_bad));RAISE EXCEPTION 'required_rejection_not_enforced:%',v_case.label;EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error NOT LIKE '%validation_failed%' THEN RAISE;END IF;END; END LOOP;
 BEGIN PERFORM public.dg_create_native_job('d1a00000-0000-4000-8000-000000000090','legacy_transfer','NONPROD-DDG-BAD-980001','biztrack_sales_order',v_header,'{}'::jsonb);RAISE EXCEPTION 'malformed_native_not_rejected';EXCEPTION WHEN OTHERS THEN NULL;END;
 BEGIN PERFORM public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000091',v_provenance||pg_catalog.jsonb_build_object('source_fingerprint',pg_catalog.repeat('b',64),'source_identifier_value','NONPROD-DDG-BAD-980002'),v_header,'{}'::jsonb);RAISE EXCEPTION 'malformed_transfer_not_rejected';EXCEPTION WHEN OTHERS THEN NULL;END;
 SELECT last_value,is_called INTO v_after_sequence,v_after_called FROM public.dg_native_job_reference_seq;IF v_after_sequence<>v_seq OR v_after_called IS DISTINCT FROM v_seq_called THEN RAISE EXCEPTION 'acceptance.sequence_changed';END IF;
END;$acceptance$;
ROLLBACK;
SELECT (SELECT count(*) FROM public.dg_native_jobs WHERE visible_identifier LIKE 'NONPROD-DDG-%') AS test_jobs_remaining,(SELECT count(*) FROM public.dg_native_job_lines WHERE line_id::text LIKE 'd1b00000-0000-4000-8000-%') AS test_lines_remaining,(SELECT count(*) FROM public.dg_native_job_create_commands WHERE command_id::text LIKE 'd1a00000-0000-4000-8000-%') AS test_command_receipts_remaining,(SELECT last_value=14 AND is_called FROM public.dg_native_job_reference_seq) AS sequence_unchanged,((SELECT count(*) FROM public.dg_native_jobs WHERE visible_identifier LIKE 'NONPROD-DDG-%')=0 AND (SELECT count(*) FROM public.dg_native_job_lines WHERE line_id::text LIKE 'd1b00000-0000-4000-8000-%')=0 AND (SELECT count(*) FROM public.dg_native_job_create_commands WHERE command_id::text LIKE 'd1a00000-0000-4000-8000-%')=0 AND (SELECT last_value=14 AND is_called FROM public.dg_native_job_reference_seq)) AS overall_acceptance_passed;
