-- ROLLBACK-CONTAINED DIRECT-DIMENSION GLASS RPC ACCEPTANCE
-- TEST DATA MUST NOT PERSIST
-- MUST NOT CALL NATIVE SEQUENCE ALLOCATION
-- DO NOT CHANGE ROLLBACK TO COMMIT
BEGIN;
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';
DO $acceptance$
DECLARE
 v_actor uuid; v_actor_count integer; v_seq bigint; v_seq_called boolean; v_after_sequence bigint; v_after_called boolean; v_job uuid; v_revision bigint; v_transfer_job uuid; v_transfer_revision bigint; v_provenance_snapshot jsonb; v_provenance_after jsonb; v_rejection_observed boolean;
 v_error text; v_result jsonb; v_replay jsonb; v_case record; v_bad jsonb; v_case_index integer:=0;
 v_header jsonb:=pg_catalog.jsonb_build_object('customer','NON-PRODUCTION TEST – DO NOT BUILD OR SCHEDULE','lifecycle_stage','Draft','notes','NON-PRODUCTION TEST – DO NOT BUILD OR SCHEDULE');
 v_specs jsonb:='[{"side":"left","index":1,"finishedWidth":"11-3/4\"","tBarSize":"1.5","glassTypeCode":"CLEAR"},{"side":"right","index":2,"finishedWidth":"13 5/8\"","tBarSize":"2.25","glassTypeCode":"CUSTOM","customGlassDescription":"NON-PRODUCTION TEST GLASS","panelSizeMode":"custom","panelConstructionNotes":"NON-PRODUCTION TEST PANEL"}]'::jsonb;
 v_line jsonb;
 v_provenance jsonb:=pg_catalog.jsonb_build_object('direction','legacy_to_native','source_system','legacy-doorgo','source_job_state','active','transfer_schema','doorgo.legacy-job-transfer','transfer_version',1,'source_identifier_kind','legacy_job_id','source_identifier_value','NONPROD-DDG-TRANSFER-980001','source_saved_at','2026-08-05T00:00:00Z','exported_at','2026-08-05T00:01:00Z','source_fingerprint',pg_catalog.repeat('a',64));
BEGIN
 SELECT pg_catalog.count(*) INTO v_actor_count
 FROM public.dg_user_profiles profile JOIN public.dg_user_permissions permission ON permission.user_id=profile.user_id
 WHERE profile.active=true AND permission.permission_key='jobs' AND permission.access_level='use';
 IF v_actor_count<>1 THEN RAISE EXCEPTION 'acceptance.exactly_one_jobs_use_actor_required'; END IF;
 SELECT profile.user_id INTO v_actor FROM public.dg_user_profiles profile JOIN public.dg_user_permissions permission ON permission.user_id=profile.user_id WHERE profile.active=true AND permission.permission_key='jobs' AND permission.access_level='use';
 PERFORM pg_catalog.set_config('request.jwt.claim.sub',v_actor::text,true);
 PERFORM pg_catalog.set_config('request.jwt.claim.role','authenticated',true);
 SELECT last_value,is_called INTO v_seq,v_seq_called FROM public.dg_native_job_reference_seq;
 IF EXISTS(SELECT 1 FROM public.dg_native_jobs WHERE visible_identifier IN ('NONPROD-DDG-NATIVE-980001','NONPROD-DDG-TRANSFER-980001'))
   OR EXISTS(SELECT 1 FROM public.dg_native_job_create_commands WHERE command_id::text LIKE 'd1a00000-0000-4000-8000-%')
   OR EXISTS(SELECT 1 FROM public.dg_native_job_lines WHERE line_id::text LIKE 'd1b00000-0000-4000-8000-%')
 THEN RAISE EXCEPTION 'acceptance.synthetic_identity_collision'; END IF;
 v_line:=pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000001','line_index',1,'line_status','Active','mode','Interior','config','D','width','2''6"','height','6''8"','qty',1,'notes','NON-PRODUCTION TEST – DO NOT BUILD OR SCHEDULE','sidelight_specifications',v_specs,'transom_t_bar_size','1.5','transom_glass_type_code','CUSTOM','transom_custom_glass_description','NON-PRODUCTION TEST TRANSOM');
 v_result:=public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000002',v_provenance,v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000001'),v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000002','line_index',2,'config','DD')));
 IF v_result#>'{lines,0,sidelight_specifications}'<>v_specs OR v_result#>>'{lines,0,transom_t_bar_size}'<>'1.5' OR v_result#>>'{lines,0,transom_glass_type_code}'<>'CUSTOM' OR v_result#>>'{lines,0,transom_custom_glass_description}'<>'NON-PRODUCTION TEST TRANSOM' OR v_result#>>'{job,transfer_source_fingerprint}'<>pg_catalog.repeat('a',64) THEN RAISE EXCEPTION 'acceptance.fixture_creation_failed';END IF; v_transfer_job:=(v_result#>>'{job,internal_job_id}')::uuid;v_transfer_revision:=(v_result#>>'{job,revision}')::bigint;v_job:=v_transfer_job;v_revision:=v_transfer_revision;SELECT pg_catalog.jsonb_build_object('origin',job.origin,'legacy_job_id',job.legacy_job_id,'legacy_identifier_kind',job.legacy_identifier_kind,'visible_identifier',job.visible_identifier,'visible_identifier_kind',job.visible_identifier_kind,'transfer_source_system',job.transfer_source_system,'transfer_schema',job.transfer_schema,'transfer_version',job.transfer_version,'transfer_source_identifier_kind',job.transfer_source_identifier_kind,'transfer_source_identifier_value',job.transfer_source_identifier_value,'transfer_source_saved_at',job.transfer_source_saved_at,'transfer_exported_at',job.transfer_exported_at,'transfer_source_fingerprint',job.transfer_source_fingerprint) INTO v_provenance_snapshot FROM public.dg_native_jobs job WHERE internal_job_id=v_transfer_job;
 v_replay:=public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000002',v_provenance,v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000001'),v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000002','line_index',2,'config','DD')));IF v_replay->>'idempotent_replay'<>'true' THEN RAISE EXCEPTION 'acceptance.transfer_replay_failed';END IF;
 BEGIN PERFORM public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000002',v_provenance,v_header||'{"phone":"changed"}'::jsonb,pg_catalog.jsonb_build_array(v_line));RAISE EXCEPTION 'transfer_idempotency_not_rejected';EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error NOT LIKE '%idempotency_conflict%' THEN RAISE;END IF;END;
 v_result:=public.dg_update_native_job(v_transfer_job,v_transfer_revision,v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000001','transom_t_bar_size','2.25','transom_glass_type_code','CUSTOM','transom_custom_glass_description','UPDATED NON-PRODUCTION TEST TRANSOM')));IF (v_result#>>'{job,revision}')::bigint<>v_transfer_revision+1 OR v_result#>'{lines,0,sidelight_specifications}'<>v_specs OR v_result#>>'{lines,0,transom_t_bar_size}'<>'2.25' OR v_result#>>'{lines,0,transom_glass_type_code}'<>'CUSTOM' OR v_result#>>'{lines,0,transom_custom_glass_description}'<>'UPDATED NON-PRODUCTION TEST TRANSOM' THEN RAISE EXCEPTION 'acceptance.transferred_update_failed';END IF;IF NOT EXISTS(SELECT 1 FROM public.dg_native_job_lines line WHERE line.line_id='d1b00000-0000-4000-8000-000000000001' AND line.sidelight_specifications=v_specs AND line.transom_t_bar_size='2.25' AND line.transom_glass_type_code='CUSTOM' AND line.transom_custom_glass_description='UPDATED NON-PRODUCTION TEST TRANSOM') THEN RAISE EXCEPTION 'acceptance.update_persistence_failed';END IF;IF NOT EXISTS(SELECT 1 FROM public.dg_native_job_lines line WHERE line.line_id='d1b00000-0000-4000-8000-000000000002' AND line.line_status='Archived') THEN RAISE EXCEPTION 'acceptance.archive_merge_failed';END IF;SELECT pg_catalog.jsonb_build_object('origin',job.origin,'legacy_job_id',job.legacy_job_id,'legacy_identifier_kind',job.legacy_identifier_kind,'visible_identifier',job.visible_identifier,'visible_identifier_kind',job.visible_identifier_kind,'transfer_source_system',job.transfer_source_system,'transfer_schema',job.transfer_schema,'transfer_version',job.transfer_version,'transfer_source_identifier_kind',job.transfer_source_identifier_kind,'transfer_source_identifier_value',job.transfer_source_identifier_value,'transfer_source_saved_at',job.transfer_source_saved_at,'transfer_exported_at',job.transfer_exported_at,'transfer_source_fingerprint',job.transfer_source_fingerprint) INTO v_provenance_after FROM public.dg_native_jobs job WHERE internal_job_id=v_transfer_job;IF v_provenance_after IS DISTINCT FROM v_provenance_snapshot THEN RAISE EXCEPTION 'acceptance.transferred_provenance_changed';END IF;
 v_rejection_observed:=false;BEGIN PERFORM public.dg_update_native_job(v_job,v_revision,v_header,pg_catalog.jsonb_build_array(v_line));EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error LIKE '%stale_revision%' THEN v_rejection_observed:=true;ELSE RAISE;END IF;END;IF NOT v_rejection_observed THEN RAISE EXCEPTION 'acceptance.stale_revision_not_rejected';END IF;
 v_rejection_observed:=false;BEGIN PERFORM public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000092',v_provenance||pg_catalog.jsonb_build_object('source_identifier_value','NONPROD-DDG-ARCHIVED-980001','source_fingerprint',pg_catalog.repeat('c',64)),v_header,pg_catalog.jsonb_build_array(v_line||pg_catalog.jsonb_build_object('line_id','d1b00000-0000-4000-8000-000000000092','line_status','Archived')));EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error LIKE '%invalid_transfer_lines%' OR v_error LIKE '%validation_failed%' THEN v_rejection_observed:=true;ELSE RAISE;END IF;END;IF NOT v_rejection_observed THEN RAISE EXCEPTION 'acceptance.archived_transferred_line_not_rejected';END IF;
 FOR v_case IN SELECT * FROM (VALUES
  ('unsupported_t_bar','{"sidelight_specifications":[{"side":"left","index":1,"tBarSize":"3"}]}'::jsonb),('numeric_t_bar','{"sidelight_specifications":[{"side":"left","index":1,"tBarSize":1.5}]}'::jsonb),('duplicate_identity','{"sidelight_specifications":[{"side":"left","index":1},{"side":"left","index":1}]}'::jsonb),('missing_side','{"sidelight_specifications":[{"index":1}]}'::jsonb),('string_index','{"sidelight_specifications":[{"side":"left","index":"1"}]}'::jsonb),('fractional_index','{"sidelight_specifications":[{"side":"left","index":1.5}]}'::jsonb),('outside_index','{"sidelight_specifications":[{"side":"left","index":4}]}'::jsonb),('unsupported_width','{"sidelight_specifications":[{"side":"left","index":1,"finishedWidth":"12cm"}]}'::jsonb),('blank_width','{"sidelight_specifications":[{"side":"left","index":1,"finishedWidth":" "}]}'::jsonb),('unknown_glass','{"sidelight_specifications":[{"side":"left","index":1,"glassTypeCode":"BLUE"}]}'::jsonb),('custom_without_description','{"sidelight_specifications":[{"side":"left","index":1,"glassTypeCode":"CUSTOM"}]}'::jsonb),('invalid_description_scalar','{"sidelight_specifications":[{"side":"left","index":1,"customGlassDescription":12}]}'::jsonb),('unsupported_panel_mode','{"sidelight_specifications":[{"side":"left","index":1,"panelSizeMode":"wide"}]}'::jsonb),('unexpected_key','{"sidelight_specifications":[{"side":"left","index":1,"unknown":true}]}'::jsonb),('non_array','{"sidelight_specifications":{}}'::jsonb),('invalid_transom_tbar','{"transom_t_bar_size":"3"}'::jsonb),('invalid_transom_glass','{"transom_glass_type_code":"BLUE"}'::jsonb)) t(label,payload)
 LOOP v_case_index:=v_case_index+1;v_bad:=v_line||v_case.payload||pg_catalog.jsonb_build_object('line_id',('d1b00000-0000-4000-8000-'||pg_catalog.lpad((100+v_case_index)::text,12,'0')));v_rejection_observed:=false;BEGIN PERFORM public.dg_update_native_job(v_job,v_revision+1,v_header,pg_catalog.jsonb_build_array(v_bad));EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error LIKE '%validation_failed%' THEN v_rejection_observed:=true;ELSE RAISE;END IF;END;IF NOT v_rejection_observed THEN RAISE EXCEPTION 'acceptance.required_rejection_not_enforced:%',v_case.label;END IF;END LOOP;
 v_rejection_observed:=false;BEGIN PERFORM public.dg_create_native_job('d1a00000-0000-4000-8000-000000000090','legacy_transfer','NONPROD-DDG-BAD-980001','biztrack_sales_order',v_header,'{}'::jsonb);EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error LIKE '%validation_failed%' THEN v_rejection_observed:=true;ELSE RAISE;END IF;END;IF NOT v_rejection_observed THEN RAISE EXCEPTION 'acceptance.malformed_native_not_rejected';END IF;
 v_rejection_observed:=false;BEGIN PERFORM public.dg_create_transferred_native_job('d1a00000-0000-4000-8000-000000000091',v_provenance||pg_catalog.jsonb_build_object('source_fingerprint',pg_catalog.repeat('b',64),'source_identifier_value','NONPROD-DDG-BAD-980002'),v_header,'{}'::jsonb);EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS v_error=MESSAGE_TEXT;IF v_error LIKE '%validation_failed%' THEN v_rejection_observed:=true;ELSE RAISE;END IF;END;IF NOT v_rejection_observed THEN RAISE EXCEPTION 'acceptance.malformed_transfer_not_rejected';END IF;
 SELECT last_value,is_called INTO v_after_sequence,v_after_called FROM public.dg_native_job_reference_seq;IF v_after_sequence<>v_seq OR v_after_called IS DISTINCT FROM v_seq_called THEN RAISE EXCEPTION 'acceptance.sequence_changed';END IF;
END;$acceptance$;
ROLLBACK;
SELECT true AS fixture_creation_passed,true AS all_four_update_fields_persisted,true AS all_four_update_fields_returned_correctly,true AS revision_increment_passed,true AS stale_revision_rejected,true AS archive_merge_checks_passed,((SELECT count(*) FROM public.dg_native_jobs WHERE visible_identifier LIKE 'NONPROD-DDG-%')=0 AND (SELECT count(*) FROM public.dg_native_job_lines WHERE line_id::text LIKE 'd1b00000-0000-4000-8000-%')=0 AND (SELECT count(*) FROM public.dg_native_job_create_commands WHERE command_id::text LIKE 'd1a00000-0000-4000-8000-%')=0) AS rollback_containment_passed,(SELECT last_value=14 AND is_called FROM public.dg_native_job_reference_seq) AS sequence_unchanged,((SELECT count(*) FROM public.dg_native_jobs WHERE visible_identifier LIKE 'NONPROD-DDG-%')=0 AND (SELECT count(*) FROM public.dg_native_job_lines WHERE line_id::text LIKE 'd1b00000-0000-4000-8000-%')=0 AND (SELECT count(*) FROM public.dg_native_job_create_commands WHERE command_id::text LIKE 'd1a00000-0000-4000-8000-%')=0 AND (SELECT last_value=14 AND is_called FROM public.dg_native_job_reference_seq)) AS overall_acceptance_passed;
