'use server';
import{getCurrentDoorGoAccess}from'@/lib/auth/current-access';import{canUse}from'@/lib/auth/access';import{createAuthenticatedSupabaseServerClient}from'@/lib/supabase/server';

export type StaffAwayInput={commandId:string;periodId:string|null;expectedRevision:number|null;staffId:string;startDate:string;endDate:string;mode:'full_day'|'partial';partialDragHours:number|null;reason:string};
type Result={ok:true;periodId:string;revision:number;startDate:string;endDate:string}|{ok:false;code:string;message:string};
const messages:Record<string,string>={permission_required:'Production use permission is required.',staff_unavailable:'Choose an active Manager roster member.',invalid_request:'Check the Staff Away dates and fields.',partial_single_working_date:'Partial Staff Away must use one normal working date.',partial_drag_excessive:'Capacity Drag must not exceed this staff member\'s configured impact for the date.',no_working_dates:'Choose a range containing at least one normal working date.',overlapping_period:'This staff member already has Staff Away overlapping the selected dates.',not_found:'This Staff Away period is no longer active.',stale_period:'This Staff Away period changed. Reopen it and try again.',invalid_range:'Choose a valid Staff Away date range.'};
const failure=(message:string):Result=>{const code=message.startsWith('staff_away.')?message.slice(11):'unavailable';return{ok:false,code,message:messages[code]??'Staff Away could not be saved. Please try again.'};};
async function authorized(){const access=await getCurrentDoorGoAccess();return canUse(access,'production')?createAuthenticatedSupabaseServerClient():null;}
export async function saveStaffAway(input:StaffAwayInput):Promise<Result>{const client=await authorized();if(!client)return failure('staff_away.permission_required');const {data,error}=await client.rpc('save_staff_away_period',{p_command_id:input.commandId,p_period_id:input.periodId,p_expected_revision:input.expectedRevision,p_staff_id:input.staffId,p_start_date:input.startDate,p_end_date:input.endDate,p_mode:input.mode,p_partial_drag_hours:input.partialDragHours,p_reason:input.reason});if(error)return failure(error.message);const row=(data??{}) as Record<string,unknown>;return{ok:true,periodId:String(row.periodId),revision:Number(row.revision??1),startDate:String(row.startDate??input.startDate),endDate:String(row.endDate??input.endDate)};}
export async function deleteStaffAway(input:{commandId:string;periodId:string;expectedRevision:number}):Promise<Result>{const client=await authorized();if(!client)return failure('staff_away.permission_required');const {data,error}=await client.rpc('delete_staff_away_period',{p_command_id:input.commandId,p_period_id:input.periodId,p_expected_revision:input.expectedRevision});if(error)return failure(error.message);const row=(data??{}) as Record<string,unknown>;return{ok:true,periodId:input.periodId,revision:input.expectedRevision+1,startDate:String(row.startDate),endDate:String(row.endDate)};}
