import type{CapacityRole,CapacityStaff,ManagerCapacityConfiguration}from'./capacity-configuration';
export type ClosureRecord={closureId:string;startDate:string;endDate:string;title:string;details:string|null;revision:number};
export type SpecialDayStaff={staffId:string;displayName:string;scheduledHours:number;productiveHours:number;capacityRole?:CapacityRole};
export type SpecialDayRecord={specialDayId:string;date:string;title:string;details:string|null;calculatedCapacity:number;revision:number;staff:SpecialDayStaff[]};
export type HolidayCandidate={holidayKey:string;name:string;date:string;enabled:boolean};
export type CapacityOverrideRecord={date:string;calculatedCapacity:number|null;overrideCapacity:number;reason:string|null;revision:number};
export type ManagerCapacityExceptions={regionCode:string;year:number;closures:ClosureRecord[];specialDays:SpecialDayRecord[];holidays:HolidayCandidate[];overrides:CapacityOverrideRecord[]};
export function configuredWorkingDaysForDate(workweeks:ManagerCapacityConfiguration['workweeks'],date:string):number[]{return workweeks.find(entry=>entry.effectiveFrom<=date)?.weekdays??[1,2,3,4,5];}
export function configuredStaffForDate(staff:CapacityStaff[],date:string,workingDays:number[],includeInactiveIds:string[]=[]):SpecialDayStaff[]{const weekday=new Date(`${date}T00:00:00Z`).getUTCDay();const ordinaryWorkingDay=workingDays.includes(weekday);const included=new Set(includeInactiveIds);return staff.filter((item)=>item.active||included.has(item.staffId)).map((item)=>{const version=item.versions.find((entry)=>entry.effectiveFrom<=date);const day=version?.weekdays.find((entry)=>entry.weekday===weekday);const fallbackProductiveHours=Math.max(0,...(version?.weekdays.map(entry=>entry.capacityHours).filter(value=>value>0)??[]));const fallbackScheduledHours=Math.max(fallbackProductiveHours,...(version?.weekdays.map(entry=>entry.scheduledHours).filter(value=>value>0)??[]));return{staffId:item.staffId,displayName:item.displayName,scheduledHours:ordinaryWorkingDay?day?.scheduledHours??0:fallbackScheduledHours,productiveHours:version?.capacityRole==='direct_production'?(ordinaryWorkingDay?day?.capacityHours??0:fallbackProductiveHours):0,capacityRole:version?.capacityRole};}).sort((left,right)=>left.displayName.localeCompare(right.displayName));}
export function exceptionalCapacity(staff:Array<Pick<SpecialDayStaff,'productiveHours'>>):number{return staff.reduce((sum,item)=>sum+item.productiveHours,0);}
