import { expect, test } from '@playwright/experimental-ct-react';
import { JobEditorWorkbenchHarness } from './JobEditorWorkbenchHarness';
import { InlineGlassHarness } from './InlineGlassHarness';

test('saved door comparison follows Swing, Jamb Width and Quantity', async ({ mount, page }, testInfo) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await mount(<JobEditorWorkbenchHarness saved/>);
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  const pane = page.locator('.door-input-pane');
  const swing = page.getByRole('combobox', { name: 'Swing', exact: true });
  const jamb = page.getByRole('combobox', { name: 'Jamb Width', exact: true });
  const quantity = page.getByRole('spinbutton', { name: 'Quantity', exact: true });
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(0);
  await swing.selectOption('LHOUT');
  await expect(swing).toHaveAttribute('data-comparison-different', 'true');
  await expect(swing).toHaveAttribute('data-last-edited', 'true');
  await expect(swing).toHaveCSS('background-color', 'rgb(224, 237, 255)');
  await jamb.selectOption('4-9/16"');
  await expect(jamb).toHaveAttribute('data-last-edited', 'true');
  await expect(swing).not.toHaveAttribute('data-last-edited');
  await expect(swing).toHaveAttribute('data-comparison-different', 'true');
  await quantity.fill('2');
  await expect(quantity).toHaveAttribute('data-last-edited', 'true');
  await expect(swing).toHaveAttribute('data-comparison-different', 'true');
  await expect(jamb).toHaveAttribute('data-comparison-different', 'true');
  await expect(swing).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await expect(jamb).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(3);
  await expect(quantity).toHaveCSS('background-color', 'rgb(207, 227, 255)');
  await page.emulateMedia({ colorScheme: 'dark' });
  await expect(swing).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await expect(jamb).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await page.screenshot({ path: testInfo.outputPath('comparison-light-theme.png') });
  await swing.selectOption('LH');
  await expect(swing).not.toHaveAttribute('data-comparison-different');
  await expect(quantity).toHaveAttribute('data-comparison-different', 'true');
  await jamb.selectOption('6-9/16"');
  await expect(jamb).not.toHaveAttribute('data-comparison-different');
  await pane.getByRole('button', { name: 'Cancel Edit', exact: true }).click();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(0);
  await swing.selectOption('LHOUT');
  await pane.getByRole('button', { name: 'Update Door', exact: true }).click();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await expect(swing).toHaveValue('LHOUT');
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(0);
});

test('editing an earlier line uses that line, while Add uses the last active line', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await mount(<JobEditorWorkbenchHarness saved lineCount={2}/>);
  const pane = page.locator('.door-input-pane');
  const swing = pane.getByRole('combobox', { name: 'Swing', exact: true });
  const edit = page.getByRole('button', { name: 'Edit', exact: true });
  await edit.last().click();
  await swing.selectOption('RHOUT');
  await pane.getByRole('button', { name: 'Update Door', exact: true }).click();
  await expect(swing).toHaveAttribute('data-comparison-different', 'true');
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(0);
  await edit.first().click();
  await expect(swing).toHaveValue('LH');
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await swing.selectOption('LHOUT');
  await pane.getByRole('button', { name: 'Cancel Edit', exact: true }).click();
  await edit.last().click();
  await expect(swing).toHaveValue('RHOUT');
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(0);
});

test('inline glass and outer fields share one recent edit', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await mount(<InlineGlassHarness/>);
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  const pane = page.locator('.door-input-pane');
  const swing = pane.getByRole('combobox', { name: 'Swing', exact: true });
  const jamb = pane.getByLabel('Jamb Width', { exact: true });
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await swing.selectOption('LHOUT');
  const glassType = pane.getByRole('combobox', { name: 'Transom Glass Type', exact: true });
  await glassType.selectOption('SATIN_ETCH');
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(1);
  await jamb.selectOption('4-9/16"');
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(1);
  await expect(swing).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await expect(glassType).toHaveAttribute('data-comparison-different', 'true');
  await expect(glassType).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await glassType.selectOption('CLEAR');
  await expect(glassType).not.toHaveAttribute('data-comparison-different');
  const roWidth = pane.getByRole('textbox', { name: 'RO Width (inches)', exact: true });
  await roWidth.fill('56');
  await roWidth.blur();
  await jamb.selectOption('6-9/16"');
  await expect(roWidth).toHaveCSS('background-color', 'rgb(243, 237, 251)');
  await roWidth.fill('54');
  await roWidth.blur();
  await expect(roWidth).not.toHaveAttribute('data-comparison-different');
  await pane.getByRole('button', { name: 'Cancel Edit', exact: true }).click();
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await expect(pane.locator('[data-comparison-different="true"]')).toHaveCount(0);
  await expect(pane.locator('[data-last-edited="true"]')).toHaveCount(0);
});

test('reopening the same line clears its recent edit', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  await mount(<JobEditorWorkbenchHarness saved/>);
  const edit = page.getByRole('button', { name: 'Edit', exact: true });
  await edit.click();
  await page.getByRole('combobox', { name: 'Swing', exact: true }).selectOption('LHOUT');
  await edit.click();
  await expect(page.locator('.door-input-pane [data-last-edited="true"]')).toHaveCount(0);
});
