import { expect, test } from '@playwright/experimental-ct-react';
import { InlineGlassHarness } from './InlineGlassHarness';

for (const viewport of [{ width: 1600, height: 900 }, { width: 900, height: 700 }, { width: 390, height: 844 }]) {
  test(`one inline edit/update/cancel lifecycle at ${viewport.width}`, async ({ mount, page }, testInfo) => {
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on('pageerror', (error) => errors.push(error.message));
    const component = await mount(<InlineGlassHarness/>);
    const pane = component.locator('#door-input-pane');
    const linesTab = component.getByRole('button', { name: 'Job Lines (1)' });
    if (await linesTab.isVisible()) await linesTab.click();
    await component.getByRole('button', { name: 'Edit', exact: true }).click();
    await expect(pane.getByRole('heading', { name: 'Glass configuration' })).toBeVisible();
    await expect(component.getByRole('dialog')).toHaveCount(0);
    await expect(pane.getByRole('button', { name: 'Edit Unit' })).toHaveCount(0);
    await expect(pane.getByLabel('Door Type', { exact: true })).toHaveValue('Original SKU');
    const result = pane.getByLabel('Calculated measurements');
    await expect(result).toContainText('94 1/2');
    await expect(result).toContainText('12 1/4');
    await page.screenshot({ path: testInfo.outputPath('inline-glass-editor.png'), fullPage: true });
    await pane.getByRole('combobox', { name: 'Construction', exact: true }).selectOption('standard');
    await expect(result).toContainText('11 5/8');
    await pane.getByRole('combobox', { name: 'Construction', exact: true }).selectOption('low-profile-quarter-sill');
    await pane.getByLabel('Door Type', { exact: true }).fill('Updated SKU');
    await pane.getByLabel('RO Height (inches)', { exact: true }).fill('96');
    await pane.getByLabel('Line Notes', { exact: true }).click();
    await expect(result).toContainText('13 1/4');
    await pane.getByRole('button', { name: 'Update Door', exact: true }).click();
    await expect(component.getByTestId('saved-lines')).toContainText('Updated SKU');
    const saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]');
    expect(saved[0].roHeight).toBe('96"');
    expect(saved[0].glassCalc.transomHeight).toBe('13 1/4"');
    if (await linesTab.isVisible()) await linesTab.click();
    await component.getByRole('button', { name: 'Edit', exact: true }).click();
    await expect(pane.getByLabel('Door Type', { exact: true })).toHaveValue('Updated SKU');
    await pane.getByLabel('Door Type', { exact: true }).fill('Discarded SKU');
    await pane.getByLabel('RO Height (inches)', { exact: true }).fill('97');
    await pane.getByRole('button', { name: 'Cancel Edit', exact: true }).click();
    await expect(component.getByTestId('saved-lines')).not.toContainText('Discarded SKU');
    expect(JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]')).toEqual(saved);
    await pane.getByRole('combobox', { name: 'Configuration', exact: true }).selectOption('With Glass');
    await expect(pane.getByRole('heading', { name: 'Glass configuration' })).toBeVisible();
    await expect(component.getByRole('dialog')).toHaveCount(0);
    await pane.getByRole('button', { name: 'Add transom', exact: true }).click();
    await pane.getByLabel('RO Width (inches)', { exact: true }).fill('54');
    await pane.getByLabel('RO Height (inches)', { exact: true }).fill('95');
    await pane.getByLabel('Line Notes', { exact: true }).click();
    await expect(pane.getByLabel('Calculated measurements')).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('inline-glass.png'), fullPage: true });
    expect(await pane.locator('.glass-unit-builder').evaluate((node) => node.scrollHeight <= node.clientHeight + 2)).toBe(true);
    expect(await pane.evaluate((node) => node.scrollWidth <= node.clientWidth + 2)).toBe(true);
    await pane.getByLabel('Door Type', { exact: true }).scrollIntoViewIfNeeded();
    await expect(pane.getByLabel('Door Type', { exact: true })).toBeInViewport();
    await pane.hover();
    await page.mouse.wheel(0, 5000);
    await expect(pane.getByRole('button', { name: 'Add Door', exact: true })).toBeInViewport();
    expect(errors).toEqual([]);
  });
}
