import { expect, test } from '@playwright/experimental-ct-react';
import { InlineGlassHarness } from './InlineGlassHarness';

test('With Glass derives composition and prevents final removal without a modal', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  const component = await mount(<InlineGlassHarness/>);
  const pane = component.locator('#door-input-pane');
  const config = pane.getByRole('combobox', { name: 'Configuration', exact: true });
  await expect(config.locator('option')).toHaveText(['D', 'DD', 'With Glass']);
  await expect(pane.getByRole('heading', { name: 'Glass configuration' })).toHaveCount(0);
  await config.selectOption('DD');
  await expect(pane.getByRole('heading', { name: 'Glass configuration' })).toHaveCount(0);
  await config.selectOption('With Glass');
  const code = pane.locator('#glass-builder-title + p');
  await expect(code).toHaveText('SD');
  await pane.getByLabel('RO Width (inches)', { exact: true }).fill('54');
  await pane.getByLabel('Line Notes', { exact: true }).click();
  await expect(pane.getByRole('combobox', { name: 'Glass Type', exact: true })).toHaveValue('CLEAR');
  await expect(pane.getByText('Status: Complete', { exact: true })).toBeVisible();
  await pane.getByRole('button', { name: 'Add right sidelight', exact: true }).click();
  await expect(code).toHaveText('SDS');
  await pane.getByRole('button', { name: 'Remove left sidelight', exact: true }).click();
  await expect(code).toHaveText('DS');
  await expect(pane.getByText('Status: Complete', { exact: true })).toBeVisible();
  const last = pane.getByRole('button', { name: 'Remove right sidelight', exact: true });
  await last.scrollIntoViewIfNeeded();
  const scrollBefore = await pane.evaluate(node => node.scrollTop);
  await last.click();
  await expect(code).toHaveText('DS');
  await expect(config).toHaveValue('With Glass');
  const toast = pane.getByRole('status').filter({ hasText: 'With Glass requires at least one glass unit.' });
  await expect(toast).toHaveText('With Glass requires at least one glass unit. Change Configuration to D or DD to remove all glass.');
  expect(await pane.evaluate(node => node.scrollTop)).toBe(scrollBefore);
  await expect(component.getByRole('dialog')).toHaveCount(0);
  await expect(pane.getByText('Status: Complete', { exact: true })).toBeVisible();
  await expect(toast).toHaveCount(0, { timeout: 6500 });
  await pane.getByRole('button', { name: 'Add Door', exact: true }).click();
  let saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]');
  expect(saved.at(-1).config).toBe('DS');
  expect(saved.at(-1).sidelightSpecifications[0].glassTypeCode).toBe('CLEAR');
  await component.getByRole('button', { name: 'Edit', exact: true }).last().click();
  await expect(config).toHaveValue('With Glass');
  await expect(code).toHaveText('DS');
  await pane.getByRole('button', { name: 'Add transom', exact: true }).click();
  await expect(code).toHaveText('T/DS');
  await pane.getByRole('button', { name: 'Remove right sidelight', exact: true }).click();
  await expect(code).toHaveText('T/D');
  await pane.getByRole('button', { name: 'Double Door', exact: true }).click();
  await expect(code).toHaveText('T/DD');
  await pane.getByRole('button', { name: 'Remove transom', exact: true }).click();
  await expect(code).toHaveText('T/DD');
  await expect(toast).toBeVisible();
  await pane.getByRole('button', { name: 'Add left sidelight', exact: true }).click();
  await expect(code).toHaveText('T/SDD');
  await pane.getByRole('button', { name: 'Remove transom', exact: true }).click();
  await expect(code).toHaveText('SDD');
  for (const plain of ['D', 'DD']) {
    page.once('dialog', dialog => dialog.accept());
    await config.selectOption(plain);
    await expect(pane.getByRole('heading', { name: 'Glass configuration' })).toHaveCount(0);
    await pane.getByRole('button', { name: plain === 'D' ? 'Update Door' : 'Add Door', exact: true }).click();
    saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]');
    expect(saved.at(-1).config).toBe(plain);
    expect(saved.at(-1).sidelightSpecifications).toEqual([]);
    expect(saved.at(-1).glassUnits).toEqual([]);
    await config.selectOption('With Glass');
    await expect(code).toHaveText('SD');
  }
});

test('T/DD resolves Custom RO before the minimum-width check', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  const component = await mount(<InlineGlassHarness/>);
  const pane = component.locator('#door-input-pane');
  await pane.getByRole('combobox', { name: 'Configuration', exact: true }).selectOption('With Glass');
  await pane.getByRole('button', { name: 'Double Door', exact: true }).click();
  await pane.getByRole('button', { name: 'Add transom', exact: true }).click();
  await pane.getByRole('button', { name: 'Remove left sidelight', exact: true }).click();
  await pane.getByRole('combobox', { name: 'Transom Glass Type', exact: true }).selectOption('CLEAR');
  await pane.getByLabel('RO Width (inches)', { exact: true }).fill('74');
  await pane.getByLabel('RO Height (inches)', { exact: true }).fill('95');
  await pane.getByLabel('Line Notes', { exact: true }).click();
  await expect(pane.getByText(/Minimum RO width is/)).toBeVisible();
  await pane.getByRole('switch', { name: 'Fit to RO', exact: true }).click();
  await expect(pane.getByText(/Minimum RO width is/)).toHaveCount(0);
  await expect(pane.getByText(/ASTRAGAL EDGE ONLY/)).toBeVisible();
  await expect(pane.getByLabel('Calculated measurements')).toContainText('71 7/8');
  await pane.getByRole('button', { name: 'Add Door', exact: true }).click();
  const saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]');
  expect(saved.at(-1).glassCalc.activeLeafWidth).toBe('35 3/4"');
  expect(saved.at(-1).glassCalc.inactiveLeafWidth).toBe('35 3/16"');
  await component.getByRole('button', { name: 'Edit', exact: true }).last().click();
  await pane.getByLabel('RO Width (inches)', { exact: true }).fill('72 9/16');
  await pane.getByLabel('Line Notes', { exact: true }).click();
  await expect(pane.getByText(/Cut inactive slab 2" from ASTRAGAL EDGE ONLY/)).toBeVisible();
  await pane.getByLabel('RO Width (inches)', { exact: true }).fill('72 1/2');
  await pane.getByLabel('Line Notes', { exact: true }).click();
  await expect(pane.getByText(/SPECIAL \/ REVIEW REQUIRED/).first()).toBeVisible();
  await expect(pane.getByText('Status: Blocked', { exact: true })).toBeVisible();
  await expect(pane.getByLabel('Calculated measurements')).toHaveCount(0);
});

test('desktop panes scroll independently and glass controls fit beside the diagram', async ({ mount, page }, testInfo) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  const component = await mount(<InlineGlassHarness manyLines/>);
  const pane = component.locator('#door-input-pane');
  const lines = component.locator('#job-lines-pane');
  await lines.getByRole('button', { name: 'Edit', exact: true }).first().click();
  const diagram = pane.locator('.glass-structure-control');
  const fields = pane.locator('.glass-builder-fields');
  const diagramBox = await diagram.boundingBox();
  const fieldsBox = await fields.boundingBox();
  expect(diagramBox!.x + diagramBox!.width).toBeLessThanOrEqual(fieldsBox!.x);
  const transomBox = await pane.getByRole('button', { name: 'Remove transom', exact: true }).boundingBox();
  const drawingBox = await diagram.locator('svg').boundingBox();
  expect(transomBox!.y + transomBox!.height).toBeLessThanOrEqual(drawingBox!.y);
  await page.screenshot({ path: testInfo.outputPath('desktop-glass-top.png'), fullPage: true });
  const rightBefore = await lines.boundingBox();
  await pane.hover();
  await page.mouse.wheel(0, 4000);
  await expect(pane.getByRole('button', { name: 'Update Door', exact: true })).toBeInViewport();
  expect(await lines.evaluate(node => node.scrollTop)).toBe(0);
  expect((await lines.boundingBox())!.y).toBe(rightBefore!.y);
  const leftScroll = await pane.evaluate(node => node.scrollTop);
  expect(leftScroll).toBeGreaterThan(0);
  await lines.hover();
  await page.mouse.wheel(0, 8000);
  await expect(lines.getByText('Archived Lines (1)', { exact: true })).toBeInViewport();
  expect(await lines.evaluate(node => node.scrollTop)).toBeGreaterThan(0);
  expect(await pane.evaluate(node => node.scrollTop)).toBe(leftScroll);
  await lines.getByText('Archived Lines (1)', { exact: true }).click();
  await lines.getByRole('button', { name: 'Restore Line', exact: true }).scrollIntoViewIfNeeded();
  await expect(lines.getByRole('button', { name: 'Restore Line', exact: true })).toBeInViewport();
  await expect(component.getByRole('button', { name: 'Save', exact: true })).toBeInViewport();
  await expect(component.getByRole('button', { name: 'Save and Exit', exact: true })).toBeInViewport();
  expect(await component.evaluate(node => node.scrollWidth <= node.clientWidth + 2)).toBe(true);
  expect(await pane.evaluate(node => node.scrollWidth <= node.clientWidth + 2)).toBe(true);
  expect(await lines.evaluate(node => node.scrollWidth <= node.clientWidth + 2)).toBe(true);
  await expect(component.getByRole('dialog')).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath('desktop-glass-bottom.png'), fullPage: true });
});
