import { expect, test } from '@playwright/experimental-ct-react';
import { InlineGlassHarness } from './InlineGlassHarness';

test('sizing switches clear inactive inputs through Add and reopen', async ({ mount, page }) => {
  await page.setViewportSize({ width: 1600, height: 900 });
  const component = await mount(<InlineGlassHarness/>);
  const pane = component.locator('#door-input-pane');
  await pane.getByRole('combobox', { name: 'Configuration', exact: true }).selectOption('DD');
  const custom = pane.getByRole('switch', { name: 'Custom Slab', exact: true });
  const fit = pane.getByRole('switch', { name: 'Fit to RO', exact: true });
  await expect(custom).not.toBeChecked();
  await expect(fit).not.toBeChecked();
  await expect(pane.getByLabel('RO Width, inches', { exact: true })).toHaveCount(0);
  await custom.click();
  await pane.getByLabel('Active Slab Width, inches', { exact: true }).fill('41-3/4');
  await pane.getByLabel('Inactive Slab Width, inches', { exact: true }).fill('35-3/4');
  await pane.getByLabel('Slab Height, inches', { exact: true }).fill('79');
  await fit.click();
  await expect(custom).not.toBeChecked();
  await expect(fit).toBeChecked();
  await expect(pane.getByLabel('Active Slab Width, inches', { exact: true })).toHaveCount(0);
  await pane.getByLabel('RO Width, inches', { exact: true }).fill('74');
  await pane.getByRole('button', { name: 'Add Door', exact: true }).click();
  let saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]').at(-1);
  expect(saved.customSlab).toBe('RO');
  expect(saved.doubleDoorSizing).toBeNull();
  expect(saved.customSlabWidth).toBeNull();
  await component.getByRole('button', { name: 'Edit', exact: true }).last().click();
  await expect(fit).toBeChecked();
  await custom.click();
  await expect(fit).not.toBeChecked();
  await expect(pane.getByLabel('RO Width, inches', { exact: true })).toHaveCount(0);
  await pane.getByLabel('Active Slab Width, inches', { exact: true }).fill('41-3/4');
  await pane.getByLabel('Inactive Slab Width, inches', { exact: true }).fill('35-3/4');
  await pane.getByLabel('Slab Height, inches', { exact: true }).fill('79');
  await pane.getByRole('button', { name: 'Update Door', exact: true }).click();
  saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]').at(-1);
  expect(saved.customSlab).toBe('WoodCustom');
  expect(saved.roWidth).toBeNull();
  await component.getByRole('button', { name: 'Edit', exact: true }).last().click();
  await expect(custom).toBeChecked();
  await custom.click();
  await expect(custom).not.toBeChecked();
  await expect(fit).not.toBeChecked();
  await pane.getByRole('button', { name: 'Update Door', exact: true }).click();
  saved = JSON.parse(await component.getByTestId('saved-lines').textContent() ?? '[]').at(-1);
  expect(saved.customSlab).toBe('No');
  expect(saved.doubleDoorSizing).toBeNull();
});
